- hosts: localhost
  become: true
  pre_tasks:
    - name: update_repositories
      yum: update_cache=yes

  tasks:
    - include: tasks/users.yml

- name: include ansible_pull playbook
  import_playbook: ansible_pull.yml

- name: include scenario1 playbook
  import_playbook: scenario1.yml

- name: include scenario2 playbook
  import_playbook: scenario2.yml

