- hosts: localhost
  become: true
  pre_tasks:
    - name: update_repositories
      yum: update_cache=yes

  tasks:
    - include: tasks/users.yml

- name: include ansible_pull playbook
  import_playbook: ansible_pull.yml

- hosts: g8-grr-centos-1
  become: true

  tasks:
    - include: tasks/flag.yml
    - include: tasks/client-1-users.yml
    - include: tasks/client-1-files.yml
