- hosts: all
  become: true
  pre_tasks:
    - name: update_repositories
      yum: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml

- hosts: grr_centos_client_1
  become: true

  tasks:
    - include: tasks/flag.yml
