- hosts: localhost
  become: true
  pre_tasks:
    - name: update_repositories
      yum: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
