# set up for scenario 1
# this is "all at once", no phases
# groups of clients of interest are grr_client_1 through grr_client_4 (currently)

# fixme: change the hosts to the real deal

# - hosts: grr_client_1
- hosts: g8-grr-centos-1
  become: true

  tasks:
    # create users
    
    - name: create bob
      user: name=bob password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create

    - name: create ghost
      user: name=ghost password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create

    - name: create linda
      user: name=linda password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create groups='wheel'

    # copy files
    
    - name: copy root files
      copy: src=files/scenario1/client-centos-1/root dest=/ owner=root group=root mode=0600

    - name: copy bob files
      copy: src=files/scenario1/client-centos-1/home/bob dest=/home owner=bob group=bob mode=0600

    - name: copy ghost files
      copy: src=files/scenario1/client-centos-1/home/ghost dest=/home owner=ghost group=ghost mode=0600

    - name: copy linda files
      copy: src=files/scenario1/client-centos-1/home/linda dest=/home owner=linda group=linda mode=0600

    - name: copy romig files
      copy: src=files/scenario1/client-centos-1/home/romig dest=/home owner=romig group=romig mode=0600

# - hosts: grr_client_2
- hosts: g8-grr-centos-2
  become: true

  tasks:
    # create users

    - name: create bob
      user: name=bob password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create

    - name: create mary
      user: name=mary password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create

    # copy files
      
    - name: copy root files
      copy: src=files/scenario1/client-centos-2/root dest=/ owner=root group=root mode=0600

    - name: copy bob files
      copy: src=files/scenario1/client-centos-2/home/bob dest=/home owner=bob group=bob mode=0600

    - name: copy mary files
      copy: src=files/scenario1/client-centos-2/home/mary dest=/home owner=mary group=mary mode=0600

    - name: copy romig files
      copy: src=files/scenario1/client-centos-2/home/romig dest=/home owner=romig group=romig mode=0600

# - hosts: grr_client_3
- hosts: g8-grr-centos-3
  become: true

  tasks: 

# - hosts: grr_client_4
- hosts: g8-grr-centos-4
  become: true

  tasks:
    # create users

    - name: create bob
      user: name=bob password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create

    - name: create mary
      user: name=mary password="$6$LqBRjHW9$Ly0CmYynwUfmNVMhuawnA4v4Xclv2YL/hITb2l6D/ayShc7KTUjUF8keT0N5m7AXJ/TZgBJe7ZMQNq/bqNg3b/" update_password=on_create

    # copy files
      
    - name: copy root files
      copy: src=files/scenario1/client-centos-4/root dest=/ owner=root group=root mode=0600

    - name: copy bob files
      copy: src=files/scenario1/client-centos-4/home/bob dest=/home owner=bob group=bob mode=0600

    - name: copy mary files
      copy: src=files/scenario1/client-centos-4/home/mary dest=/home owner=mary group=mary mode=0600

