- name: copy root files
  copy: src=files/client-centos-1/root dest=/root owner=root group=root mode=0600

- name: copy bob files
  copy: src=files/client-centos-1/home/bob dest=/home owner=bob group=bob mode=0600

- name: copy ghost files
  copy: src=files/client-centos-1/home/ghost dest=/home owner=ghost group=ghost mode=0600

- name: copy linda files
  copy: src=files/client-centos-1/home/linda dest=/home owner=linda group=linda mode=0600

- name: copy romig files
  copy: src=files/client-centos-1/home/romig dest=/home owner=romig group=romig mode=0600

